seed: 7
cuda: 0 # use_gpu
env:
  env_type: pomdp
  env_name: Block-Picking-v0

  num_eval_tasks: 10 # num of eval episodes

train:
  # 2000*50=100K steps
  num_iters: 2000 # number meta-training iterates
  num_init_rollouts_pool: 5 # before training
  num_rollouts_per_iter: 1
  buffer_size: 1e5 # we should full buffer size as VRM

  num_updates_per_iter: 0.2 # equiv to "equal"
  # Let's fix len=64 for fair comparison with VRM
  # VRM uses batch_size=4, which may be too small?
  batch_size: 32 # to tune based on sampled_seq_len
  sampled_seq_len: -1 # -1 is all, or positive integer.
  sample_weight_baseline: 0.0 # VRM adds weight

eval:
  eval_stochastic: false # also eval stochastic policy
  log_interval: 4 # 10 num of iters
  save_interval: 100 # -1
  log_tensorboard: true

policy:
  arch: lstm # [lstm, gru]
  algo: sac # [td3, sac]

  action_embedding_size: 16 # 0
  state_embedding_size: 32
  rnn_hidden_size: 128 

  dqn_layers: [128, 128]
  policy_layers: [128, 128]
  lr: 0.0003
  gamma: 0.99
  tau: 0.005

  # sac alpha
  entropy_alpha: 0.01 # tend to be det policy...
  automatic_entropy_tuning: true
  alpha_lr: 0.001

  # td3 noise 
  ## since we normalize action space to [-1, 1]
  ## the noise std is absolute value
  exploration_noise: 0.1 
  target_noise: 0.2
  target_noise_clip: 0.5

  # advisor
  alpha: 20

  # behavior cloning
  bc_w: 0.5

  # BC + SAC/SAC-D
  bc_perct: 0.1